version: '3.7'
services:
  nginx:
    image: nginx:latest
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    links:
      - php7
    volumes:
      - ./:/moodle
      - ./.docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
  php7:
    build: ./.docker/php7
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/moodle
      - ~/.composer:/root/.composer
    depends_on:
      - db
    links:
      - db
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - .docker/volumes/postgres/data:/var/lib/postgresql/data
      - .docker/volumes/postgres/dump:/docker-entrypoint-initdb.d
    env_file:
      - .env